# Generated by Django 5.2.7 on 2025-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_todoitem_is_completed_todoitem_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='todoitem',
            table='api_todoitem',
        ),
    ]
