# Generated by Django 5.2.7 on 2025-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todoitem_options_remove_todoitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
